(DEFINE (PROBLEM BARMAN-LOOP-BASE-4)
 (:DOMAIN BARMAN)
 (:OBJECTS L2 - LEVEL
           L1 - LEVEL
           L0 - LEVEL
           DISPENSER11 - DISPENSER
           DISPENSER10 - DISPENSER
           DISPENSER9 - DISPENSER
           DISPENSER8 - DISPENSER
           DISPENSER7 - DISPENSER
           DISPENSER6 - DISPENSER
           DISPENSER5 - DISPENSER
           DISPENSER4 - DISPENSER
           DISPENSER3 - DISPENSER
           DISPENSER2 - DISPENSER
           DISPENSER1 - DISPENSER
           COCKTAIL11 - COCKTAIL
           COCKTAIL10 - COCKTAIL
           COCKTAIL9 - COCKTAIL
           COCKTAIL8 - COCKTAIL
           COCKTAIL7 - COCKTAIL
           COCKTAIL6 - COCKTAIL
           COCKTAIL5 - COCKTAIL
           COCKTAIL4 - COCKTAIL
           COCKTAIL3 - COCKTAIL
           COCKTAIL2 - COCKTAIL
           COCKTAIL1 - COCKTAIL
           INGREDIENT11 - INGREDIENT
           INGREDIENT10 - INGREDIENT
           INGREDIENT9 - INGREDIENT
           INGREDIENT8 - INGREDIENT
           INGREDIENT7 - INGREDIENT
           INGREDIENT6 - INGREDIENT
           INGREDIENT5 - INGREDIENT
           INGREDIENT4 - INGREDIENT
           INGREDIENT3 - INGREDIENT
           INGREDIENT2 - INGREDIENT
           INGREDIENT1 - INGREDIENT
           RIGHT - HAND
           LEFT - HAND
           SHAKER1 - SHAKER
           BASE0-6028 - SHOT
           BASE1-6027 - SHOT
           BASE2-6026 - SHOT
           BASE3-6025 - SHOT)

 (:INIT
  (COCKTAIL-PART2 COCKTAIL11 INGREDIENT10)
  (COCKTAIL-PART1 COCKTAIL11 INGREDIENT4)
  (COCKTAIL-PART2 COCKTAIL10 INGREDIENT11)
  (COCKTAIL-PART1 COCKTAIL10 INGREDIENT4)
  (COCKTAIL-PART2 COCKTAIL9 INGREDIENT6)
  (COCKTAIL-PART1 COCKTAIL9 INGREDIENT4)
  (COCKTAIL-PART2 COCKTAIL8 INGREDIENT6)
  (COCKTAIL-PART1 COCKTAIL8 INGREDIENT7)
  (COCKTAIL-PART2 COCKTAIL7 INGREDIENT8)
  (COCKTAIL-PART1 COCKTAIL7 INGREDIENT5)
  (COCKTAIL-PART2 COCKTAIL6 INGREDIENT7)
  (COCKTAIL-PART1 COCKTAIL6 INGREDIENT2)
  (COCKTAIL-PART2 COCKTAIL5 INGREDIENT11)
  (COCKTAIL-PART1 COCKTAIL5 INGREDIENT2)
  (COCKTAIL-PART2 COCKTAIL4 INGREDIENT2)
  (COCKTAIL-PART1 COCKTAIL4 INGREDIENT11)
  (COCKTAIL-PART2 COCKTAIL3 INGREDIENT1)
  (COCKTAIL-PART1 COCKTAIL3 INGREDIENT4)
  (COCKTAIL-PART2 COCKTAIL2 INGREDIENT5)
  (COCKTAIL-PART1 COCKTAIL2 INGREDIENT11)
  (COCKTAIL-PART2 COCKTAIL1 INGREDIENT2)
  (COCKTAIL-PART1 COCKTAIL1 INGREDIENT11)
  (NEXT L1 L2)
  (NEXT L0 L1)
  (SHAKER-LEVEL SHAKER1 L0)
  (SHAKER-EMPTY-LEVEL SHAKER1 L0)
  (HANDEMPTY RIGHT)
  (HANDEMPTY LEFT)
  (EMPTY SHAKER1)
  (CLEAN SHAKER1)
  (DISPENSES DISPENSER11 INGREDIENT11)
  (DISPENSES DISPENSER10 INGREDIENT10)
  (DISPENSES DISPENSER9 INGREDIENT9)
  (DISPENSES DISPENSER8 INGREDIENT8)
  (DISPENSES DISPENSER7 INGREDIENT7)
  (DISPENSES DISPENSER6 INGREDIENT6)
  (DISPENSES DISPENSER5 INGREDIENT5)
  (DISPENSES DISPENSER4 INGREDIENT4)
  (DISPENSES DISPENSER3 INGREDIENT3)
  (DISPENSES DISPENSER2 INGREDIENT2)
  (DISPENSES DISPENSER1 INGREDIENT1)
  (ONTABLE SHAKER1)
  (EMPTY BASE0-6028)
  (EMPTY BASE1-6027)
  (EMPTY BASE2-6026)
  (EMPTY BASE3-6025)
  (CLEAN BASE0-6028)
  (CLEAN BASE1-6027)
  (CLEAN BASE2-6026)
  (CLEAN BASE3-6025)
  (ONTABLE BASE0-6028)
  (ONTABLE BASE1-6027)
  (ONTABLE BASE2-6026)
  (ONTABLE BASE3-6025))
 (:GOAL
  (AND (CONTAINS BASE0-6028 COCKTAIL10)
       (CONTAINS BASE1-6027 COCKTAIL10)
       (CONTAINS BASE2-6026 COCKTAIL10)
       (CONTAINS BASE3-6025 COCKTAIL10))))